package vue;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import metier.Traitement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author julien
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGenererPlaning = new javax.swing.JButton();
        jComboBoxSelectionnerSalle = new javax.swing.JComboBox<>();
        jComboBoxSelectionnerDate = new javax.swing.JComboBox<>();
        jCheckBoxVoirSeanceLibre = new javax.swing.JCheckBox();
        textFieldRecherche = new java.awt.TextField();
        jButtonRechercherFilm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlanning = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 700));

        jButtonGenererPlaning.setText("Générer le planing");
        jButtonGenererPlaning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenererPlaningActionPerformed(evt);
            }
        });

        jComboBoxSelectionnerSalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSelectionnerSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectionnerSalleActionPerformed(evt);
            }
        });

        jComboBoxSelectionnerDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSelectionnerDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectionnerDateActionPerformed(evt);
            }
        });

        jCheckBoxVoirSeanceLibre.setText("Voir les séances libres");
        jCheckBoxVoirSeanceLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVoirSeanceLibreActionPerformed(evt);
            }
        });

        textFieldRecherche.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldRecherche.setMinimumSize(new java.awt.Dimension(69, 24));
        textFieldRecherche.setText("");
        textFieldRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldRechercheActionPerformed(evt);
            }
        });

        jButtonRechercherFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechercherFilmActionPerformed(evt);
            }
        });

        jTablePlanning.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTablePlanning.setAutoscrolls(false);
        jTablePlanning.setFocusable(false);
        jTablePlanning.setRequestFocusEnabled(false);
        jTablePlanning.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTablePlanning);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonGenererPlaning, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxSelectionnerSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxSelectionnerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxVoirSeanceLibre)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRechercherFilm)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 520, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGenererPlaning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRechercherFilm)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxSelectionnerSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxSelectionnerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBoxVoirSeanceLibre))
                    .addComponent(textFieldRecherche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenererPlaningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenererPlaningActionPerformed
        try {
            Traitement.genererPlaning();
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGenererPlaningActionPerformed

    private void textFieldRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldRechercheActionPerformed

    private void jButtonRechercherFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechercherFilmActionPerformed
        String film = textFieldRecherche.getText();
        if (film.length() > 0) {
            Traitement.rechercherFilm(film);
        }
    }//GEN-LAST:event_jButtonRechercherFilmActionPerformed

    private void jCheckBoxVoirSeanceLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxVoirSeanceLibreActionPerformed
        Boolean etat = jCheckBoxVoirSeanceLibre.isSelected();
        Traitement.voirSeanceLibre(etat);
    }//GEN-LAST:event_jCheckBoxVoirSeanceLibreActionPerformed

    private void jComboBoxSelectionnerSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectionnerSalleActionPerformed
        String salle = (String) jComboBoxSelectionnerSalle.getSelectedItem();
        Traitement.selectionnerSalle(salle);
    }//GEN-LAST:event_jComboBoxSelectionnerSalleActionPerformed

    private void jComboBoxSelectionnerDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectionnerDateActionPerformed
        String date = (String) jComboBoxSelectionnerDate.getSelectedItem();
        Traitement.selectionnerDate(date);
    }//GEN-LAST:event_jComboBoxSelectionnerDateActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenererPlaning;
    private javax.swing.JButton jButtonRechercherFilm;
    private javax.swing.JCheckBox jCheckBoxVoirSeanceLibre;
    private javax.swing.JComboBox<String> jComboBoxSelectionnerDate;
    private javax.swing.JComboBox<String> jComboBoxSelectionnerSalle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlanning;
    private java.awt.TextField textFieldRecherche;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton get_jButtonGenererPlaning() {
        return this.jButtonGenererPlaning;
    }
    
    public javax.swing.JButton get_jButtonRechercherFilm() {
        return this.jButtonRechercherFilm;
    }
    
    public javax.swing.JCheckBox get_jCheckBoxVoirSeanceLibre() {
        return this.jCheckBoxVoirSeanceLibre;
    }
    
    public javax.swing.JComboBox<String> get_jComboBoxSelectionnerDate() {
        return this.jComboBoxSelectionnerDate;
    }
    
    public javax.swing.JComboBox<String> get_jComboBoxSelectionnerSalle() {
        return this.jComboBoxSelectionnerSalle;
    }
    
    public javax.swing.JScrollPane get_jScrollPane1() {
        return this.jScrollPane1;
    }
    
    public javax.swing.JTable get_jTablePlanning() {
        return this.jTablePlanning;
    }
    
    public java.awt.TextField get_textFieldRecherche() {
        return this.textFieldRecherche;
    }
    
}
